FROM apify/actor-python-playwright:3.10-1.39.0

LABEL org.opencontainers.image.source=https://github.com/shamhi/HamsterKombatBot
WORKDIR /app


RUN apt-get update && apt-get install -y build-essential

COPY requirements.txt .
RUN pip3 install --upgrade pip setuptools wheel loguru && \
    pip3 install --no-cache-dir -r requirements.txt

RUN playwright install --with-deps chromium

WORKDIR /app

COPY . .


RUN python3 main.py  -a 2
